# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Spatial_Analysis_Agent
                                 A QGIS plugin
 A plugin integration between QGIS and Large Language Model (LLM) for Spatial Analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-12
        copyright            : (C) 2024 by GIBD
        email                : teakinboyewa@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# Guard: ensure sys.stderr/stdout are not None before any library imports.
# QGIS Python environment sometimes sets these to None, which crashes
# numpy, pandas, and other libraries that write warnings during import.
import sys as _sys, io as _io
if _sys.stderr is None:
    _sys.stderr = _io.StringIO()
if _sys.stdout is None:
    _sys.stdout = _io.StringIO()

# Pre-import libraries whose DLLs crash when first loaded in a worker thread.
# pyarrow in particular causes "Windows fatal exception: access violation"
# if its native DLL is first loaded outside the main thread.
# We suppress the QGIS exception hook during these imports so that
# compatibility warnings (e.g. numpy version mismatch) don't pop up
# as error dialogs — they are non-fatal for plugin loading.
try:
    _orig_excepthook = _sys.excepthook
    _sys.excepthook = lambda *args: None  # suppress during pre-import
    import warnings as _warnings
    with _warnings.catch_warnings():
        _warnings.simplefilter("ignore")
        try:
            import pyarrow  # noqa: F401
        except Exception:
            pass
        try:
            import geopandas  # noqa: F401
        except Exception:
            pass
    _sys.excepthook = _orig_excepthook
except Exception:
    pass


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Spatial_Analysis_Agent class from file Spatial_Analysis_Agent.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SpatialAnalysisAgent import SpatialAnalysisAgent
    return SpatialAnalysisAgent(iface)